[package]
name = "toralize"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.155"
redhook = "2.0"
byteorder = "1.5.0"
log = "0.4.21"

[lib]
path = "src/lib.rs"
crate-type = ["dylib"]

[[bin]]
name="toralized"
path="src/main.rs"
